name: Ekstrak Berkas ZIP dan Push

on: [push]

permissions:
  contents: write # Memberikan izin GitHub Actions untuk menulis/mengubah repositori

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repositori
      uses: actions/checkout@v4

    - name: Ekstrak ZIP menggunakan perintah Linux
      run: |
        mkdir -p ./ybaserocky-wallet-v6
        unzip -q baserocky-wallet-v6.zip -d ./baserocky-wallet-v6

    - name: Commit dan Push Hasil Ekstraksi
      run: |
        # Konfigurasi identitas git di server virtual
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        
        # Tambahkan semua hasil ekstrak ke staging area
        git add ./baserocky-wallet-v6
        
        # Periksa apakah ada perubahan baru untuk di-commit
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Otomatis: Ekstrak berkas ZIP ke baserocky-wallet-v6"
          git push
        else
          echo "Tidak ada perubahan baru untuk di-commit."
        fi
        
