name: Ekstrak Berkas ZIP

on: [push]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repositori
      uses: actions/checkout@v4

    - name: Ekstrak ZIP
      uses: ammarahm-ed/extract-action@v1.1
      with:
        # Ganti dengan nama berkas zip Anda
        file: "nama_file_kamu.zip" 
        # Ganti dengan folder tujuan ekstrak
        out: "./folder_tujuan"    
